name: yeah

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Post comment
      run: |
        curl --request POST \
          --url '${{ github.event.pull_request.comments_url }}' \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"body": "yeah."}'
